# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Will Lawrence's Blog
tagline:          Development, Javascript, and interesting technologies fused with business topics and startup ideas
url:              https://willhlaw.github.io/willhlaw/
paginate:         1
baseurl:          http://username.github.io/willhlaw/
author:
  name:           Will Lawrence
  url:            https://twitter.com/willhlaw
  email:          will.lawrence@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/willhlaw/willhlaw.github.io
